server:
  port: 9990
  servlet:
    context-path: /em
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.93.179.232:3308/em_db
    username: root
    password: 123456
  data:
    redis:
      host: 47.93.179.232
      port: 6379
      database: 0




mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.em.parent.entity

sa-token:
  token-name: satoken
  active-timeout: -1
  timeout: 259200
  is-concurrent: true
  is-share: false
  token-style: uuid
  is-log: true

#easy-trans:
#  #启用redis缓存 如果不用redis请设置为false
#  is-enable-redis: false
#  #启用全局翻译(拦截所有responseBody进行自动翻译)，如果关闭需要手动调用翻译方法或者方法加注解，具体看文档
#  is-enable-global: true
#  #启用平铺模式
#  is-enable-tile: true
#  #字典缓存放到redis 微服务模式请开启
#  dict-use-redis: false
#  # ruoyi相关的请开启
#  is-enable-map-result: true
#  # MP为 3.5.3.2版本以上的3.x 版本请设置为true，否则可能会出现找不到对应方法的问题
#  mp-new: false